
def build(bld):
	print('build project ' + bld.path.abspath())
        bld(features='c cprogram',
            source='test.c',
            target='test',
            includes     = ['../include/'],
            cflags       = ['-O2', '-Wall', '-g'],
	    install_path = './test/'	    
	)
#gcc -Wall -g -I/usr/local/include/ -o test example.c
