APPNAME='gdb_breakpoint'

def build(bld):
	print('build project ' + bld.path.abspath())
        bld(features   = 'c cprogram',
            source     = 'gdb_breakpoint.c',
            target     = APPNAME,
            uselib     = 'BFD',
            cflags     = ['-O2', '-Wall','-std=gnu99'],
	)
